[package]
name = "ri"
version = "0.1.0"
authors = ["Keegan Myers"]
edition = "2018"

[dependencies]
ropey = "1.3.1"
termion = "1.5.6"
arboard = "2.0.0"
tui = "0.16.0"
env_logger = "0.8.3"
argh = "0.1.5"
log = "0.4.17"
log4rs = "1.2.0"
clap = "3.2.22"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_plain = "1.0.0"
anyhow = "1.0.65"
syntect = "5.0.0"
uuid = {version = "1.2.1", features = ["v4"]}
postage = "0.5.0"
tokio = {version = "1.21.2", features = ["full"]}

#![feature(alloc_system)]
#![feature(global_allocator, allocator_api)]
