[package]
name = "ri"
version = "0.1.0"
authors = ["Keegan Myers"]
edition = "2018"

[dependencies]
ropey = "1.3.1"
#clap = "3.0.0-beta.2"
termion = "1.5.6"
arboard = "2.0.0"
tui = "0.16.0"
env_logger = "0.8.3"
argh = "0.1.5"
log = "0.4.17"
clap = "3.2.22"
strum = "0.24.1"
strum_macros = "0.24.3"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_plain = "1.0.0"
anyhow = "1.0.65"
syntect = "5.0.0"
tui-logger = "0.8.0"

#![feature(alloc_system)]
#![feature(global_allocator, allocator_api)]
